# Generated by Django 5.1.5 on 2025-05-21 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=100)),
                ("capacite", models.PositiveIntegerField()),
                ("dimensions", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CategorieDepense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TypeBande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Bande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_bande", models.CharField(max_length=50, unique=True)),
                ("periode", models.CharField(max_length=100)),
                ("effectif_depart", models.PositiveIntegerField()),
                (
                    "batiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ispace.batiment",
                    ),
                ),
                (
                    "type_bande",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ispace.typebande",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepenseAvicole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("quantite", models.FloatField(blank=True, null=True)),
                ("prix_unitaire", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "bande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ispace.bande"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ispace.categoriedepense",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("quantite", models.PositiveIntegerField(blank=True, null=True)),
                ("date_ajout", models.DateField(auto_now_add=True)),
                (
                    "batiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ispace.batiment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mortalite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("effectif", models.PositiveIntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "bande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ispace.bande"
                    ),
                ),
            ],
        ),
    ]
