# Generated by Django 5.1.5 on 2025-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ispace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="batiment",
            name="type",
            field=models.CharField(
                choices=[
                    ("elevage", "Élevage"),
                    ("nourriture", "Stockage de nourriture"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=20,
            ),
        ),
    ]
