# Generated by Django 5.1.5 on 2025-05-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ispace", "0002_batiment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bande",
            name="periode",
        ),
        migrations.AddField(
            model_name="bande",
            name="date_debut",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bande",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
    ]
