# Generated by Django 5.1.5 on 2025-05-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ispace", "0003_remove_bande_periode_bande_date_debut_bande_date_fin"),
    ]

    operations = [
        migrations.AddField(
            model_name="depenseavicole",
            name="montant_fcfa",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Montant (FCFA)"
            ),
        ),
    ]
